/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salesmanagementsystem;


import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class addCustomerUI extends javax.swing.JFrame {
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addCustomerUI.class.getName());

    /**
     * Creates new form addCustomerUI
     */
    public addCustomerUI() {
        initComponents();
    }
    
    private User loggedInUser; // a constructor accepts values from the previous frame
    
    public addCustomerUI(User user) {
        this.loggedInUser = user; // save for later use
        initComponents();
        
        uName.setText(loggedInUser.getName());
        
        pack();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toCManagementUIButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cxName = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        toMainUIButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 50, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(663, 573));

        uName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        uName.setForeground(new java.awt.Color(103, 111, 157));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Customer");

        toCManagementUIButton.setBackground(new java.awt.Color(249, 177, 122));
        toCManagementUIButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toCManagementUIButton.setForeground(new java.awt.Color(18, 21, 36));
        toCManagementUIButton.setText("Back");
        toCManagementUIButton.setBorder(null);
        toCManagementUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCManagementUIButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact");

        cxName.setBackground(new java.awt.Color(66, 71, 105));
        cxName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxName.setForeground(new java.awt.Color(255, 255, 255));
        cxName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(249, 177, 122), new java.awt.Color(249, 177, 122)));
        cxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNameActionPerformed(evt);
            }
        });

        contact.setBackground(new java.awt.Color(66, 71, 105));
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(249, 177, 122), new java.awt.Color(249, 193, 122)));

        addCustomerButton.setBackground(new java.awt.Color(249, 177, 122));
        addCustomerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addCustomerButton.setForeground(new java.awt.Color(18, 21, 36));
        addCustomerButton.setText("Add");
        addCustomerButton.setBorder(null);
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        toMainUIButton.setBackground(new java.awt.Color(249, 177, 122));
        toMainUIButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toMainUIButton.setForeground(new java.awt.Color(18, 21, 36));
        toMainUIButton.setText("Main Menu");
        toMainUIButton.setBorder(null);
        toMainUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMainUIButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cxName)
                                .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))))
                .addGap(0, 169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(toCManagementUIButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toMainUIButton, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cxName)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(21, 21, 21)
                .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(toCManagementUIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toMainUIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNameActionPerformed
        
    }//GEN-LAST:event_cxNameActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        String cName = cxName.getText().trim();
        String phone = contact.getText().trim();
        int uId = loggedInUser.getUserId();
        
        if (cName.isEmpty() || phone.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter name and Contact");
            return;
        }
        
        CustomerDAO cDAO = new CustomerDAO();
        Customer customer = cDAO.addCustomer(cName, phone, uId);
        
        if (customer != null){
           JOptionPane.showMessageDialog(this,"Succesfull! Customer Id: "+customer.getCustomerId());
           cxName.setText("");
           contact.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Unsuccesful!", "Something went wrong", JOptionPane.ERROR_MESSAGE);
            cxName.setText("");
            contact.setText("");
        }
        
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void toCManagementUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCManagementUIButtonActionPerformed
        new CustomerManagementUI(loggedInUser).setVisible(true);
    }//GEN-LAST:event_toCManagementUIButtonActionPerformed

    private void toMainUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMainUIButtonActionPerformed
        new mainUi(loggedInUser).setVisible(true);
    }//GEN-LAST:event_toMainUIButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addCustomerUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField cxName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton toCManagementUIButton;
    private javax.swing.JButton toMainUIButton;
    private javax.swing.JLabel uName;
    // End of variables declaration//GEN-END:variables
}
