/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salesmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class deleteProductUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(deleteProductUI.class.getName());

    /**
     * Creates new form deleteProductUI
     */
    public deleteProductUI() {
        initComponents();
    }

    
    private User loggedInUser;
    private Product toDelProduct;
    
    public deleteProductUI(User user) {
        this.loggedInUser = user; // save for later use
        initComponents();
        
        uName.setText(loggedInUser.getName());
        
        pack();
        setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productId = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProductId = new javax.swing.JTextField();
        searchProductButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uPrice = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        toMainUIButton = new javax.swing.JButton();
        toPManagementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productId.setBackground(new java.awt.Color(45, 50, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Product");
        jLabel1.setToolTipText("");

        uName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        uName.setForeground(new java.awt.Color(103, 111, 157));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Id");

        ProductId.setBackground(new java.awt.Color(66, 71, 105));
        ProductId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProductId.setForeground(new java.awt.Color(255, 255, 255));
        ProductId.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(249, 177, 122), new java.awt.Color(249, 177, 122)));

        searchProductButton.setBackground(new java.awt.Color(249, 177, 122));
        searchProductButton.setForeground(new java.awt.Color(18, 21, 66));
        searchProductButton.setText("Search");
        searchProductButton.setBorder(null);
        searchProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Product Name: ");

        pName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unit Price: ");

        uPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uPrice.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stock: ");

        quantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantity.setForeground(new java.awt.Color(255, 255, 255));

        deleteButton.setBackground(new java.awt.Color(249, 177, 122));
        deleteButton.setForeground(new java.awt.Color(18, 21, 36));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        toMainUIButton.setBackground(new java.awt.Color(249, 177, 122));
        toMainUIButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toMainUIButton.setForeground(new java.awt.Color(18, 21, 36));
        toMainUIButton.setText("Main Menu");
        toMainUIButton.setToolTipText("");
        toMainUIButton.setBorder(null);
        toMainUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMainUIButtonActionPerformed(evt);
            }
        });

        toPManagementButton.setBackground(new java.awt.Color(249, 177, 122));
        toPManagementButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toPManagementButton.setForeground(new java.awt.Color(18, 21, 36));
        toPManagementButton.setText("Back");
        toPManagementButton.setBorder(null);
        toPManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPManagementButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productIdLayout = new javax.swing.GroupLayout(productId);
        productId.setLayout(productIdLayout);
        productIdLayout.setHorizontalGroup(
            productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productIdLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(productIdLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productIdLayout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(productIdLayout.createSequentialGroup()
                                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ProductId, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(pName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productIdLayout.createSequentialGroup()
                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(productIdLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(toPManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productIdLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productIdLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toMainUIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        productIdLayout.setVerticalGroup(
            productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productIdLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ProductId, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(searchProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(productIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toPManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toMainUIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductButtonActionPerformed
       int pId = Integer.parseInt(ProductId.getText());
        int uId = loggedInUser.getUserId();
        
        String input = ProductId.getText();
        
        if(input.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter product Id", "Failed!", JOptionPane.ERROR_MESSAGE);
            pName.setText("");
            uPrice.setText("");
            quantity.setText("");
            return;
        }
        else{
        ProductDAO dao = new ProductDAO();
        toDelProduct = dao.setProduct(pId, uId);
        
        pName.setText(toDelProduct.getProductName());
        uPrice.setText(String.valueOf(toDelProduct.getUnitPrice()));
        quantity.setText(String.valueOf(toDelProduct.getQuantity()));
        ProductId.setText("");
        }
    }//GEN-LAST:event_searchProductButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String msg = "";
        ProductDAO dao = new ProductDAO();
        
        msg = dao.deleteProduct(toDelProduct.getProductId());
        
        if(msg.isEmpty()){
            JOptionPane.showMessageDialog(this, "Something went wrong", "Failed!", JOptionPane.ERROR_MESSAGE);
            ProductId.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, msg);
            ProductId.setText("");
            pName.setText("");
            uPrice.setText("");
            quantity.setText("");
        }
    
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void toPManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPManagementButtonActionPerformed
        new productManagementUI(loggedInUser).setVisible(true);
    }//GEN-LAST:event_toPManagementButtonActionPerformed

    private void toMainUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMainUIButtonActionPerformed
        new mainUi(loggedInUser).setVisible(true);
    }//GEN-LAST:event_toMainUIButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new deleteProductUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ProductId;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel pName;
    private javax.swing.JPanel productId;
    private javax.swing.JLabel quantity;
    private javax.swing.JButton searchProductButton;
    private javax.swing.JButton toMainUIButton;
    private javax.swing.JButton toPManagementButton;
    private javax.swing.JLabel uName;
    private javax.swing.JLabel uPrice;
    // End of variables declaration//GEN-END:variables
}
